import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import local from "next/font/local";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const gotham = local({
  src: [
    { path: "./fonts/SVN-Gotham.otf", weight: "800" },
    { path: "./fonts/SVN-Gotham Regular.otf", weight: "400" },
    { path: "./fonts/SVN-Gotham Light.otf", weight: "300" },
  ],
  variable: "--font-gotham",
});
const playfair = local({
  src: [
    {
      path: "./fonts/PlayfairDisplay.ttf",
      weight: "800",
    },
    { path: "./fonts/PlayfairDisplay-Black.ttf", weight: "900" },
    { path: "./fonts/PlayfairDisplay-Medium.ttf", weight: "500" },
  ],
  variable: "--font-playfair",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${gotham.variable} ${playfair.variable}`}>
        <Header></Header>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
